version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: discord.js-commando
    versions:
    - 0.11.1
    - 0.12.0
    - 0.12.1
    - 0.12.2
